version: '3.3'

services:
  postgres:
    image: postgres:latest   
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser        
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase      
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - eshop_network
      - postgres_network      

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" 
    depends_on:
      - postgres 
    networks:
      - postgres_network
      
  rabbitmq:
    image: rabbitmq:3-management   
    container_name: rabbitmq_container
    restart: always
    hostname: eshop_queue
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: admin 
    ports:
      - "5673:5672"   # Ensure this is exposed properly
      - "15673:15672" # RabbitMQ management UI
    networks:
      - eshop_network
  

volumes:
  postgres_data:

networks:
  eshop_network:
  postgres_network:
