<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Modular.Common\Modular.Common.csproj" />
  </ItemGroup>

</Project>
